[19/Nov/2022 14:38:31] ERROR [LearningPlatform:67] An error occurred
Traceback (most recent call last):
  File "/Users/chortlehoort/dev/github/nss/python/LearningPlatform/LearningAPI/views/student_view.py", line 54, in retrieve
    personality = StudentPersonality.objects.getz(student=student)
AttributeError: 'Manager' object has no attribute 'getz'
[19/Nov/2022 14:44:05] ERROR [LearningPlatform:67] An error occurred
Traceback (most recent call last):
  File "/Users/chortlehoort/dev/github/nss/python/LearningPlatform/LearningAPI/views/student_view.py", line 54, in retrieve
    personality = StudentPersonality.objects.getz(student=student)
AttributeError: 'Manager' object has no attribute 'getz'
[19/Nov/2022 14:48:05] ERROR [LearningPlatform:67] AttributeError("'Manager' object has no attribute 'getz'")
Traceback (most recent call last):
  File "/Users/chortlehoort/dev/github/nss/python/LearningPlatform/LearningAPI/views/student_view.py", line 54, in retrieve
    personality = StudentPersonality.objects.getz(student=student)
AttributeError: 'Manager' object has no attribute 'getz'
